### PR TITLE
Add symlinks from system

### LINKED ISSUE #11: Make an opt-in way to use system ICDs
This can be done by a post-link script. These scripts are run once per version when conda installs the package for the first time.

### PR DESCRIPTION
**Pull request by isuruf**
Fixes #11

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for this--I think this will be quite helpful, although there is a possibility for the links to go out of date.

**Comment by inducer** [comment]
CI died with a mysterious git permission error.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by inducer** [comment]
Thanks for working on this!

**Pull request merged**
