### PR TITLE
remove activate.sh

### LINKED ISSUE #29: Noisy warning on environment activation when ffmpeg or libopencv are installed in an environment on Linux
### Comment:

Since https://github.com/conda-forge/openvino-feedstock/pull/73 has been merged, all the new environments in which I install `opencv` or `ffmpeg` get a big and scary warning:

~~~
WARNING: No ICDs were found. Either,
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or
- Make your system-wide implementation visible by installing ocl-icd-system conda package.
~~~

This warning actually comes from the `ocl-icd` package, that comes from the `libopencv --> libopenvino-intel-gpu-plugin --> ocl-icd` dependency chain. The warning is printed on every environment activation, and kind of confuses users, especially the one that do not care or even do not know anything about OpenCL. I do not have any specific opinion on OpenCL so removing `ocl-icd-system` may be perfectly fine for me, but do you think we could avoid this extremely noisy warning? 

fyi @conda-forge/ffmpeg @conda-forge/opencv @conda-forge/openvino @conda-forge/ocl-icd

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please rerender

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please rerender

**Comment by erykoff** [comment]
Hi -- just wondering what is keeping this from getting merged, which will fix downstream issues.  cc @isuruf

**Comment by matthiasdiener** [comment]
Any objections to merging this @isuruf @inducer?

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
